version: "3.8"

services:
  cliente1-backend:
    build: .
    container_name: cliente1-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=n8n
      - DB_USER=postgres
      - DB_PASSWORD=897f44b440db0d6c11dc
    networks:
      - default
      - n8n_external

networks:
  n8n_external:
    external: true
    name: n8n_n8n_net
